// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs2dkwjFzZcrU823wqnM_Z5RN32GRLAhI',
    appId: '1:1059743094728:web:a1e7be68876d7463c412fd',
    messagingSenderId: '1059743094728',
    projectId: 'workout-app-383e0',
    authDomain: 'workout-app-383e0.firebaseapp.com',
    storageBucket: 'workout-app-383e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX8pmJ1MVNukkRrp7NzfC4EjY1WBC26VE',
    appId: '1:1059743094728:android:42050e4ca2b84990c412fd',
    messagingSenderId: '1059743094728',
    projectId: 'workout-app-383e0',
    storageBucket: 'workout-app-383e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr4DwhYduQ-UgoZwcXTOfaJR1qmId5Quw',
    appId: '1:1059743094728:ios:68c18d740dd86978c412fd',
    messagingSenderId: '1059743094728',
    projectId: 'workout-app-383e0',
    storageBucket: 'workout-app-383e0.firebasestorage.app',
    iosBundleId: 'com.mobilecomputing.workoutapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr4DwhYduQ-UgoZwcXTOfaJR1qmId5Quw',
    appId: '1:1059743094728:ios:d04f3aaf5ada914ec412fd',
    messagingSenderId: '1059743094728',
    projectId: 'workout-app-383e0',
    storageBucket: 'workout-app-383e0.firebasestorage.app',
    iosBundleId: 'com.example.workoutApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs2dkwjFzZcrU823wqnM_Z5RN32GRLAhI',
    appId: '1:1059743094728:web:df65e617572c22e2c412fd',
    messagingSenderId: '1059743094728',
    projectId: 'workout-app-383e0',
    authDomain: 'workout-app-383e0.firebaseapp.com',
    storageBucket: 'workout-app-383e0.firebasestorage.app',
  );
}